import type { UserStatus, FuelerDashboardData } from "@/types/erau";
import type { FuelRequest } from "@/types/fuelRequest";

// Canned responses used when USE_MOCK_DATA=true, so the app is usable without campus network
// access. Taken verbatim from real payloads captured on 2026-09-20.

export const mockUserStatus: UserStatus = {
  environment: "production",
  user: {
    selectedResourceId: "0",
    etaPersId: "0",
    selectedResourceSlotSum: "0",
    phoneNumber: "",
    defaultPage: "",
    fileLabel: "",
    apLast4: "",
    firstName: "",
    email: "",
    accountMissing: false,
    loggedIn: false,
    selectedActivityId: "0",
    campus: "",
    pin: "",
    lastName: "",
    roles: [],
    userId: "0",
    themeIsDark: "false",
    enabled: false,
    erauId: "",
    inspectorNum: "",
    signatureId: "0",
  },
};

export const mockFuelerDashboardData: FuelerDashboardData = {
  sampleMessage: "fueler data from the server (mock)",
};

export const mockFuelRequests: FuelRequest[] = [
  {
      "DATE_MODIFIED": "2026-09-21 15:35:22.176586 -04:00",
      "DATE_CREATED": "2026-09-21 15:35:22.176586 -04:00",
      "RESOURCE_ID": 161,
      "DETAILS": {
        "PARKING_SPOT_ID": 79,
        "OIL": 0,
        "PARKING_SPOT": {
          "DATE_MODIFIED": "2021-07-20 12:55:59.000000 -04:00",
          "ETA_PARK_SPOT_ID": 49,
          "DATE_CREATED": "2021-07-20 12:55:59.000000 -04:00",
          "PARKING_SPOT_ID": 79,
          "RESOURCES": "",
          "CAMPUS": "DB",
          "RESOURCE_ID": "",
          "ENABLED": 1,
          "PREVENT_AF_REQ": 0,
          "OBSOLETE": 0,
          "NAME": "B 15"
        },
        "DENY_REASON_DETAILS": "",
        "REQUEST_FUEL_OIL_ID": 417368,
        "FUEL": 1,
        "THIRD_PARTY_DATA": {
          "REQUESTED_SERVICE": "Fill to tabs",
          "REQUESTED_AMOUNT": ""
        },
        "DENY_REASON_ID": ""
      },
      "MODE": "Aircraft",
      "RESPONDING_USER_ID": "",
      "REQUEST_ID": 2720037,
      "ACTIVITY_ID": 1166087,
      "DATE_COMPLETED": "",
      "INITIATING_USER_ID": 26047,
      "PARENT_ID": 0,
      "INITIATOR": {
        "DATE_MODIFIED": "2026-09-21 15:35:00.143975 -04:00",
        "DATE_CREATED": "2026-08-23 16:38:37.227043 -04:00",
        "USER_ID": 26047,
        "EMAIL": "mahoneb6@my.erau.edu",
        "LAST_NAME": "Mahoney",
        "SELECTED_RESOURCE_SLOT_SUM": "",
        "ERAU_ID": "2725592",
        "FIRST_NAME": "Brendan",
        "NAME": "Brendan Mahoney (2725592)",
        "EFC_CAMPUS": "DB",
        "LOC_ID": 46,
        "ETA_ID": "2725592",
        "ROLES": "pilot",
        "SELECTED_ACTIVITY_ID": 1166087,
        "USERNAME": "mahoneb6",
        "ENABLED": 1,
        "SELECTED_RESOURCE_ID": 161,
        "PHONE_NUMBER": "",
        "ETA_PERS_ID": 62667
      },
      "NOTES": "",
      "TYPE_ID": 3,
      "PARENTED": 0,
      "REQUEST_TYPE": "Fuel/Oil",
      "STATUS_ID": 5,
      "ACTIVITY": {
        "INSTRUCTOR_NO_ACCOUNT": 0,
        "PARKING_SPOT": {
          "DATE_MODIFIED": "2021-07-20 12:55:59.000000 -04:00",
          "ETA_PARK_SPOT_ID": 49,
          "DATE_CREATED": "2021-07-20 12:55:59.000000 -04:00",
          "PARKING_SPOT_ID": 79,
          "RESOURCES": "",
          "CAMPUS": "DB",
          "RESOURCE_ID": "",
          "ENABLED": 1,
          "PREVENT_AF_REQ": 0,
          "OBSOLETE": 0,
          "NAME": "B 15"
        },
        "END_HOBBS": "",
        "RESOURCE_ID": 161,
        "OBSERVERS": 0,
        "START_TACH": 3516.2,
        "INSTRUCTOR_USER_ID": 11089,
        "START_DATETIME": "2026-09-21 15:34:59.883882 -04:00",
        "CANCEL_REASON": "",
        "ACT_COMMENT": "",
        "STUDENT1_DISP_NAME": "Brendan Mahoney",
        "STUDENT1_USER_ID": 26047,
        "STATUS": "PreFlight Complete",
        "INSTRUCTOR_DISP_NAME": "Jacob Zielinski",
        "END_TACH": "",
        "ETA_AUTH": "true",
        "STUDENT2_DISP_NAME": "",
        "ACTIVITY_TYPE": "Dual",
        "STUDENT2_USER": {},
        "INSTRUCTOR_USER": {
          "DATE_MODIFIED": "2026-09-20 03:00:01.647305 -04:00",
          "DATE_CREATED": "2022-09-19 10:23:29.000000 -04:00",
          "USER_ID": 11089,
          "EMAIL": "zielinj3@my.erau.edu",
          "LAST_NAME": "Zielinski",
          "SELECTED_RESOURCE_SLOT_SUM": "",
          "ERAU_ID": "2594818",
          "FIRST_NAME": "Jacob",
          "NAME": "Jacob Zielinski (2594818)",
          "EFC_CAMPUS": "DB",
          "LOC_ID": 46,
          "ETA_ID": "2594818",
          "ROLES": "instr. pilot;pilot",
          "SELECTED_ACTIVITY_ID": "",
          "USERNAME": "zielinj3",
          "ENABLED": 1,
          "SELECTED_RESOURCE_ID": "",
          "PHONE_NUMBER": "",
          "ETA_PERS_ID": 51005
        },
        "RESOURCE_CAMPUS": "DB",
        "COMPLETION_REQUESTED": "",
        "FUEL_LEVEL": "",
        "OFFSITE_RETURN": "",
        "STUDENT2_USER_ID": "",
        "DATE_MODIFIED": "2026-09-21 15:35:00.159932 -04:00",
        "PARKING_SPOT_ID": 79,
        "STUDENT2_NO_ACCOUNT": 0,
        "ETA_ACT_ID": 8817927,
        "STATUS_CODE": 15,
        "ACTIVITY_ID": 1166087,
        "START_HOBBS": 1503.7,
        "ACTIVITY_TYPE_ID": 2,
        "END_DATETIME": "",
        "STUDENT1_NO_ACCOUNT": 0,
        "STUDENT1_USER": {
          "DATE_MODIFIED": "2026-09-21 15:35:00.143975 -04:00",
          "DATE_CREATED": "2026-08-23 16:38:37.227043 -04:00",
          "USER_ID": 26047,
          "EMAIL": "mahoneb6@my.erau.edu",
          "LAST_NAME": "Mahoney",
          "SELECTED_RESOURCE_SLOT_SUM": "",
          "ERAU_ID": "2725592",
          "FIRST_NAME": "Brendan",
          "NAME": "Brendan Mahoney (2725592)",
          "EFC_CAMPUS": "DB",
          "LOC_ID": 46,
          "ETA_ID": "2725592",
          "ROLES": "pilot",
          "SELECTED_ACTIVITY_ID": 1166087,
          "USERNAME": "mahoneb6",
          "ENABLED": 1,
          "SELECTED_RESOURCE_ID": 161,
          "PHONE_NUMBER": "",
          "ETA_PERS_ID": 62667
        },
        "DESTINATION_ID": 4,
        "USER_ROLE": "Student 1"
      },
      "RESOURCE": {
        "DATE_CREATED": "2021-07-20 12:51:47.000000 -04:00",
        "RESOURCE_ID": 161,
        "PARKING_SPOT_LAST_KNOWN_ID": 79,
        "RESOURCE_CAT": "Aircraft",
        "MAKE": "Cessna",
        "CAMPUS": "DB",
        "SERIAL_NUM": "172S669",
        "ETA_RESOURCE_ID": 4383,
        "LAST_KNOWN_TACH": "",
        "INSPECTION_BIT": 0,
        "PEDAL_EXT": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID_AS_EFC": 79,
        "INSPECTION_PLAN_ID": 2,
        "DATE_MODIFIED": "2026-09-21 13:09:14.881539 -04:00",
        "PARKING_SPOT_DETAILS": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID": 49,
        "PEDAL_POSITION": "",
        "VFR": 0,
        "FUEL_THRESHOLD": 34,
        "LAST_RAMP_IN_HOBBS": 1503.7,
        "MODEL": "172S NAV III",
        "LAST_RAMP_IN_TACH": 3516.2,
        "PARKING_SPOT_LAST_KNOWN_NAME": "B 15",
        "OBSOLETE": 0,
        "NAME": "N832ER",
        "RESOURCE_TYPE_NAME": "Cessna 172S Nav3",
        "ACTIVE_PEDAL_REQUEST": 0,
        "HOBBS_TIME": "1503.7",
        "PEDAL_ABILITY": 0,
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_NAME_AS_EFC": "B 15",
        "FPC_ABILITY": 0,
        "NEXT_TACH_INSPECTION": "",
        "PARKING_SPOT_LAST_KNOWN_ID_AS_ETA": 49,
        "QRCODE1": "https://webapps.erau.edu/flight-clipboard/resourceqr/N832ER-K-1638363023767",
        "ENABLED": 1,
        "ETA_RESOURCE_CAT": "Aircraft",
        "PARKING_FBO": "",
        "TACH_TIME": "3516.2",
        "QRCODE2": "https://webapps.erau.edu/flight-clipboard/resourceqr/N832ER-P-1638363026313"
      }
    },
    {
      "DATE_MODIFIED": "2026-09-21 15:26:24.920700 -04:00",
      "DATE_CREATED": "2026-09-21 15:29:24.918000 -04:00",
      "RESOURCE_ID": 749,
      "DETAILS": {
        "PARKING_SPOT_ID": 95,
        "OIL": 0,
        "PARKING_SPOT": {
          "DATE_MODIFIED": "2021-07-20 12:56:23.000000 -04:00",
          "ETA_PARK_SPOT_ID": 57,
          "DATE_CREATED": "2021-07-20 12:56:23.000000 -04:00",
          "PARKING_SPOT_ID": 95,
          "RESOURCES": "",
          "CAMPUS": "DB",
          "RESOURCE_ID": "",
          "ENABLED": 1,
          "PREVENT_AF_REQ": 0,
          "OBSOLETE": 0,
          "NAME": "B 23"
        },
        "DENY_REASON_DETAILS": "",
        "REQUEST_FUEL_OIL_ID": 417366,
        "FUEL": 1,
        "THIRD_PARTY_DATA": {
          "REQUESTED_SERVICE": "Fill to tabs",
          "REQUESTED_AMOUNT": ""
        },
        "DENY_REASON_ID": ""
      },
      "MODE": "Aircraft",
      "RESPONDING_USER_ID": "",
      "REQUEST_ID": 2719975,
      "ACTIVITY_ID": "",
      "DATE_COMPLETED": "",
      "INITIATING_USER_ID": 2,
      "PARENT_ID": 0,
      "INITIATOR": {
        "DATE_MODIFIED": "2023-11-22 13:35:07.478000 -05:00",
        "DATE_CREATED": "2023-11-22 13:35:07.478000 -05:00",
        "USER_ID": 2,
        "EMAIL": "noreply@erau.edu",
        "LAST_NAME": "Automated",
        "SELECTED_RESOURCE_SLOT_SUM": "",
        "ERAU_ID": "0000000",
        "FIRST_NAME": "Request",
        "NAME": "Request Automated (0000000)",
        "EFC_CAMPUS": "",
        "LOC_ID": "",
        "ETA_ID": "",
        "ROLES": "",
        "SELECTED_ACTIVITY_ID": "",
        "USERNAME": "system",
        "ENABLED": 1,
        "SELECTED_RESOURCE_ID": "",
        "PHONE_NUMBER": "",
        "ETA_PERS_ID": -1
      },
      "NOTES": "",
      "TYPE_ID": 3,
      "PARENTED": 0,
      "REQUEST_TYPE": "Fuel/Oil",
      "STATUS_ID": 5,
      "RESOURCE": {
        "DATE_CREATED": "2023-06-28 11:41:01.421484 -04:00",
        "RESOURCE_ID": 749,
        "PARKING_SPOT_LAST_KNOWN_ID": 95,
        "RESOURCE_CAT": "Aircraft",
        "MAKE": "Cessna",
        "CAMPUS": "DB",
        "SERIAL_NUM": "172S12976",
        "ETA_RESOURCE_ID": 5025,
        "LAST_KNOWN_TACH": "",
        "INSPECTION_BIT": 0,
        "PEDAL_EXT": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID_AS_EFC": 95,
        "INSPECTION_PLAN_ID": 61,
        "DATE_MODIFIED": "2026-09-21 15:26:24.906421 -04:00",
        "PARKING_SPOT_DETAILS": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID": 57,
        "PEDAL_POSITION": "",
        "VFR": 0,
        "FUEL_THRESHOLD": 34,
        "LAST_RAMP_IN_HOBBS": 4023.2,
        "MODEL": "172S NAV III",
        "LAST_RAMP_IN_TACH": 3010,
        "PARKING_SPOT_LAST_KNOWN_NAME": "B 23",
        "OBSOLETE": 0,
        "NAME": "N941ER",
        "RESOURCE_TYPE_NAME": "Cessna 172S Nav3",
        "ACTIVE_PEDAL_REQUEST": 0,
        "HOBBS_TIME": "4023.2",
        "PEDAL_ABILITY": 0,
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_NAME_AS_EFC": "B 23",
        "FPC_ABILITY": 0,
        "NEXT_TACH_INSPECTION": "",
        "PARKING_SPOT_LAST_KNOWN_ID_AS_ETA": 57,
        "QRCODE1": "https://webapps.erau.edu/flight-clipboard/resourceqr/N941ER-K-1784655126211",
        "ENABLED": 1,
        "ETA_RESOURCE_CAT": "Aircraft",
        "PARKING_FBO": "",
        "TACH_TIME": "3010.0",
        "QRCODE2": "https://webapps.erau.edu/flight-clipboard/resourceqr/N941ER-P-1784655125146"
      }
    },
    {
      "DATE_MODIFIED": "2026-09-22 01:03:58.969916 -04:00",
      "DATE_CREATED": "2026-09-22 01:06:58.967000 -04:00",
      "RESOURCE_ID": 161,
      "DETAILS": {
        "PARKING_SPOT_ID": 107,
        "OIL": 0,
        "PARKING_SPOT": {
          "DATE_MODIFIED": "2021-07-20 12:56:43.000000 -04:00",
          "ETA_PARK_SPOT_ID": 224,
          "DATE_CREATED": "2021-07-20 12:56:43.000000 -04:00",
          "PARKING_SPOT_ID": 107,
          "RESOURCES": "",
          "CAMPUS": "DB",
          "RESOURCE_ID": "",
          "ENABLED": 1,
          "PREVENT_AF_REQ": 0,
          "OBSOLETE": 0,
          "NAME": "B 29"
        },
        "DENY_REASON_DETAILS": "",
        "REQUEST_FUEL_OIL_ID": 417618,
        "FUEL": 1,
        "THIRD_PARTY_DATA": {
          "REQUESTED_SERVICE": "Fill to tabs",
          "REQUESTED_AMOUNT": ""
        },
        "DENY_REASON_ID": ""
      },
      "MODE": "Aircraft",
      "RESPONDING_USER_ID": "",
      "REQUEST_ID": 2721415,
      "ACTIVITY_ID": "",
      "DATE_COMPLETED": "",
      "INITIATING_USER_ID": 2,
      "PARENT_ID": 0,
      "INITIATOR": {
        "DATE_MODIFIED": "2023-11-22 13:35:07.478000 -05:00",
        "DATE_CREATED": "2023-11-22 13:35:07.478000 -05:00",
        "USER_ID": 2,
        "EMAIL": "noreply@erau.edu",
        "LAST_NAME": "Automated",
        "SELECTED_RESOURCE_SLOT_SUM": "",
        "ERAU_ID": "0000000",
        "FIRST_NAME": "Request",
        "NAME": "Request Automated (0000000)",
        "EFC_CAMPUS": "",
        "LOC_ID": "",
        "ETA_ID": "",
        "ROLES": "",
        "SELECTED_ACTIVITY_ID": "",
        "USERNAME": "system",
        "ENABLED": 1,
        "SELECTED_RESOURCE_ID": "",
        "PHONE_NUMBER": "",
        "ETA_PERS_ID": -1
      },
      "NOTES": "",
      "TYPE_ID": 3,
      "PARENTED": 0,
      "REQUEST_TYPE": "Fuel/Oil",
      "STATUS_ID": 5,
      "RESOURCE": {
        "DATE_CREATED": "2021-07-20 12:51:47.000000 -04:00",
        "RESOURCE_ID": 161,
        "PARKING_SPOT_LAST_KNOWN_ID": 107,
        "RESOURCE_CAT": "Aircraft",
        "MAKE": "Cessna",
        "CAMPUS": "DB",
        "SERIAL_NUM": "172S669",
        "ETA_RESOURCE_ID": 4383,
        "LAST_KNOWN_TACH": "",
        "INSPECTION_BIT": 0,
        "PEDAL_EXT": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID_AS_EFC": 107,
        "INSPECTION_PLAN_ID": 2,
        "DATE_MODIFIED": "2026-09-22 01:03:58.954408 -04:00",
        "PARKING_SPOT_DETAILS": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID": 224,
        "PEDAL_POSITION": "",
        "VFR": 0,
        "FUEL_THRESHOLD": 34,
        "LAST_RAMP_IN_HOBBS": 1508.2,
        "MODEL": "172S NAV III",
        "LAST_RAMP_IN_TACH": 3519.2,
        "PARKING_SPOT_LAST_KNOWN_NAME": "B 29",
        "OBSOLETE": 0,
        "NAME": "N832ER",
        "RESOURCE_TYPE_NAME": "Cessna 172S Nav3",
        "ACTIVE_PEDAL_REQUEST": 0,
        "HOBBS_TIME": "1508.2",
        "PEDAL_ABILITY": 0,
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_NAME_AS_EFC": "B 29",
        "FPC_ABILITY": 0,
        "NEXT_TACH_INSPECTION": "",
        "PARKING_SPOT_LAST_KNOWN_ID_AS_ETA": 224,
        "QRCODE1": "https://webapps.erau.edu/flight-clipboard/resourceqr/N832ER-K-1638363023767",
        "ENABLED": 1,
        "ETA_RESOURCE_CAT": "Aircraft",
        "PARKING_FBO": "",
        "TACH_TIME": "3519.2",
        "QRCODE2": "https://webapps.erau.edu/flight-clipboard/resourceqr/N832ER-P-1638363026313"
      }
    },
    {
      "DATE_MODIFIED": "2026-09-22 00:57:48.862654 -04:00",
      "DATE_CREATED": "2026-09-22 01:00:48.860000 -04:00",
      "RESOURCE_ID": 157,
      "DETAILS": {
        "PARKING_SPOT_ID": 41,
        "OIL": 0,
        "PARKING_SPOT": {
          "DATE_MODIFIED": "2021-07-20 12:53:49.000000 -04:00",
          "ETA_PARK_SPOT_ID": 27,
          "DATE_CREATED": "2021-07-20 12:53:49.000000 -04:00",
          "PARKING_SPOT_ID": 41,
          "RESOURCES": "",
          "CAMPUS": "DB",
          "RESOURCE_ID": "",
          "ENABLED": 1,
          "PREVENT_AF_REQ": 0,
          "OBSOLETE": 0,
          "NAME": "A 21"
        },
        "DENY_REASON_DETAILS": "",
        "REQUEST_FUEL_OIL_ID": 417598,
        "FUEL": 1,
        "THIRD_PARTY_DATA": {
          "REQUESTED_SERVICE": "Fill to tabs",
          "REQUESTED_AMOUNT": ""
        },
        "DENY_REASON_ID": ""
      },
      "MODE": "Aircraft",
      "RESPONDING_USER_ID": "",
      "REQUEST_ID": 2721419,
      "ACTIVITY_ID": "",
      "DATE_COMPLETED": "",
      "INITIATING_USER_ID": 2,
      "PARENT_ID": 0,
      "INITIATOR": {
        "DATE_MODIFIED": "2023-11-22 13:35:07.478000 -05:00",
        "DATE_CREATED": "2023-11-22 13:35:07.478000 -05:00",
        "USER_ID": 2,
        "EMAIL": "noreply@erau.edu",
        "LAST_NAME": "Automated",
        "SELECTED_RESOURCE_SLOT_SUM": "",
        "ERAU_ID": "0000000",
        "FIRST_NAME": "Request",
        "NAME": "Request Automated (0000000)",
        "EFC_CAMPUS": "",
        "LOC_ID": "",
        "ETA_ID": "",
        "ROLES": "",
        "SELECTED_ACTIVITY_ID": "",
        "USERNAME": "system",
        "ENABLED": 1,
        "SELECTED_RESOURCE_ID": "",
        "PHONE_NUMBER": "",
        "ETA_PERS_ID": -1
      },
      "NOTES": "",
      "TYPE_ID": 3,
      "PARENTED": 0,
      "REQUEST_TYPE": "Fuel/Oil",
      "STATUS_ID": 5,
      "RESOURCE": {
        "DATE_CREATED": "2021-07-20 12:51:41.000000 -04:00",
        "RESOURCE_ID": 157,
        "PARKING_SPOT_LAST_KNOWN_ID": 41,
        "RESOURCE_CAT": "Aircraft",
        "MAKE": "Cessna",
        "CAMPUS": "DB",
        "SERIAL_NUM": "172S12664",
        "ETA_RESOURCE_ID": 4384,
        "LAST_KNOWN_TACH": "",
        "INSPECTION_BIT": 0,
        "PEDAL_EXT": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID_AS_EFC": 41,
        "INSPECTION_PLAN_ID": 2,
        "DATE_MODIFIED": "2026-09-22 00:57:48.843276 -04:00",
        "PARKING_SPOT_DETAILS": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID": 27,
        "PEDAL_POSITION": "",
        "VFR": 0,
        "FUEL_THRESHOLD": 34,
        "LAST_RAMP_IN_HOBBS": 5930.2,
        "MODEL": "172S NAV III",
        "LAST_RAMP_IN_TACH": 4393.3,
        "PARKING_SPOT_LAST_KNOWN_NAME": "A 21",
        "OBSOLETE": 0,
        "NAME": "N820ER",
        "RESOURCE_TYPE_NAME": "Cessna 172S Nav3",
        "ACTIVE_PEDAL_REQUEST": 0,
        "HOBBS_TIME": "5930.2",
        "PEDAL_ABILITY": 0,
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_NAME_AS_EFC": "A 21",
        "FPC_ABILITY": 0,
        "NEXT_TACH_INSPECTION": "",
        "PARKING_SPOT_LAST_KNOWN_ID_AS_ETA": 27,
        "QRCODE1": "https://webapps.erau.edu/flight-clipboard/resourceqr/N820ER-K-1638363006909",
        "ENABLED": 1,
        "ETA_RESOURCE_CAT": "Aircraft",
        "PARKING_FBO": "",
        "TACH_TIME": "4393.3",
        "QRCODE2": "https://webapps.erau.edu/flight-clipboard/resourceqr/N820ER-P-1638363009369"
      }
    },
    {
      "DATE_MODIFIED": "2026-09-22 00:52:24.094906 -04:00",
      "DATE_CREATED": "2026-09-22 00:55:24.920000 -04:00",
      "RESOURCE_ID": 403,
      "DETAILS": {
        "PARKING_SPOT_ID": 153,
        "OIL": 0,
        "PARKING_SPOT": {
          "DATE_MODIFIED": "2021-07-20 12:57:50.000000 -04:00",
          "ETA_PARK_SPOT_ID": 79,
          "DATE_CREATED": "2021-07-20 12:57:50.000000 -04:00",
          "PARKING_SPOT_ID": 153,
          "RESOURCES": "",
          "CAMPUS": "DB",
          "RESOURCE_ID": "",
          "ENABLED": 1,
          "PREVENT_AF_REQ": 0,
          "OBSOLETE": 0,
          "NAME": "C 23"
        },
        "DENY_REASON_DETAILS": "",
        "REQUEST_FUEL_OIL_ID": 417616,
        "FUEL": 1,
        "THIRD_PARTY_DATA": {
          "REQUESTED_SERVICE": "Fill to tabs",
          "REQUESTED_AMOUNT": ""
        },
        "DENY_REASON_ID": ""
      },
      "MODE": "Aircraft",
      "RESPONDING_USER_ID": "",
      "REQUEST_ID": 2721409,
      "ACTIVITY_ID": "",
      "DATE_COMPLETED": "",
      "INITIATING_USER_ID": 2,
      "PARENT_ID": 0,
      "INITIATOR": {
        "DATE_MODIFIED": "2023-11-22 13:35:07.478000 -05:00",
        "DATE_CREATED": "2023-11-22 13:35:07.478000 -05:00",
        "USER_ID": 2,
        "EMAIL": "noreply@erau.edu",
        "LAST_NAME": "Automated",
        "SELECTED_RESOURCE_SLOT_SUM": "",
        "ERAU_ID": "0000000",
        "FIRST_NAME": "Request",
        "NAME": "Request Automated (0000000)",
        "EFC_CAMPUS": "",
        "LOC_ID": "",
        "ETA_ID": "",
        "ROLES": "",
        "SELECTED_ACTIVITY_ID": "",
        "USERNAME": "system",
        "ENABLED": 1,
        "SELECTED_RESOURCE_ID": "",
        "PHONE_NUMBER": "",
        "ETA_PERS_ID": -1
      },
      "NOTES": "",
      "TYPE_ID": 3,
      "PARENTED": 0,
      "REQUEST_TYPE": "Fuel/Oil",
      "STATUS_ID": 5,
      "RESOURCE": {
        "DATE_CREATED": "2022-07-06 12:41:03.000000 -04:00",
        "RESOURCE_ID": 403,
        "PARKING_SPOT_LAST_KNOWN_ID": 153,
        "RESOURCE_CAT": "Aircraft",
        "MAKE": "Cessna",
        "CAMPUS": "DB",
        "SERIAL_NUM": "172S12822",
        "ETA_RESOURCE_ID": 4822,
        "LAST_KNOWN_TACH": "",
        "INSPECTION_BIT": 0,
        "PEDAL_EXT": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID_AS_EFC": 153,
        "INSPECTION_PLAN_ID": 61,
        "DATE_MODIFIED": "2026-09-22 00:52:24.076607 -04:00",
        "PARKING_SPOT_DETAILS": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID": 79,
        "PEDAL_POSITION": "",
        "VFR": 0,
        "FUEL_THRESHOLD": 34,
        "LAST_RAMP_IN_HOBBS": 5302.4,
        "MODEL": "172S NAV III",
        "LAST_RAMP_IN_TACH": 3913.9,
        "PARKING_SPOT_LAST_KNOWN_NAME": "C 23",
        "OBSOLETE": 0,
        "NAME": "N816ER",
        "RESOURCE_TYPE_NAME": "Cessna 172S Nav3",
        "ACTIVE_PEDAL_REQUEST": 0,
        "HOBBS_TIME": "5302.4",
        "PEDAL_ABILITY": 0,
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_NAME_AS_EFC": "C 23",
        "FPC_ABILITY": 0,
        "NEXT_TACH_INSPECTION": "",
        "PARKING_SPOT_LAST_KNOWN_ID_AS_ETA": 79,
        "QRCODE1": "https://webapps.erau.edu/flight-clipboard/resourceqr/N816ER-K-1657126139605",
        "ENABLED": 1,
        "ETA_RESOURCE_CAT": "Aircraft",
        "PARKING_FBO": "",
        "TACH_TIME": "3913.9",
        "QRCODE2": "https://webapps.erau.edu/flight-clipboard/resourceqr/N816ER-P-1657126143081"
      }
    },
    {
      "DATE_MODIFIED": "2026-09-22 00:32:47.279688 -04:00",
      "DATE_CREATED": "2026-09-22 00:35:47.277000 -04:00",
      "RESOURCE_ID": 1401,
      "DETAILS": {
        "PARKING_SPOT_ID": 17,
        "OIL": 0,
        "PARKING_SPOT": {
          "DATE_MODIFIED": "2021-07-20 12:53:08.000000 -04:00",
          "ETA_PARK_SPOT_ID": 15,
          "DATE_CREATED": "2021-07-20 12:53:08.000000 -04:00",
          "PARKING_SPOT_ID": 17,
          "RESOURCES": "",
          "CAMPUS": "DB",
          "RESOURCE_ID": "",
          "ENABLED": 1,
          "PREVENT_AF_REQ": 0,
          "OBSOLETE": 0,
          "NAME": "A 09"
        },
        "DENY_REASON_DETAILS": "",
        "REQUEST_FUEL_OIL_ID": 417596,
        "FUEL": 1,
        "THIRD_PARTY_DATA": {
          "REQUESTED_SERVICE": "Top Off",
          "REQUESTED_AMOUNT": ""
        },
        "DENY_REASON_ID": ""
      },
      "MODE": "Aircraft",
      "RESPONDING_USER_ID": "",
      "REQUEST_ID": 2721393,
      "ACTIVITY_ID": "",
      "DATE_COMPLETED": "",
      "INITIATING_USER_ID": 2,
      "PARENT_ID": 0,
      "INITIATOR": {
        "DATE_MODIFIED": "2023-11-22 13:35:07.478000 -05:00",
        "DATE_CREATED": "2023-11-22 13:35:07.478000 -05:00",
        "USER_ID": 2,
        "EMAIL": "noreply@erau.edu",
        "LAST_NAME": "Automated",
        "SELECTED_RESOURCE_SLOT_SUM": "",
        "ERAU_ID": "0000000",
        "FIRST_NAME": "Request",
        "NAME": "Request Automated (0000000)",
        "EFC_CAMPUS": "",
        "LOC_ID": "",
        "ETA_ID": "",
        "ROLES": "",
        "SELECTED_ACTIVITY_ID": "",
        "USERNAME": "system",
        "ENABLED": 1,
        "SELECTED_RESOURCE_ID": "",
        "PHONE_NUMBER": "",
        "ETA_PERS_ID": -1
      },
      "NOTES": "",
      "TYPE_ID": 3,
      "PARENTED": 0,
      "REQUEST_TYPE": "Fuel/Oil",
      "STATUS_ID": 5,
      "RESOURCE": {
        "DATE_CREATED": "2024-07-22 07:41:26.744511 -04:00",
        "RESOURCE_ID": 1401,
        "PARKING_SPOT_LAST_KNOWN_ID": 17,
        "RESOURCE_CAT": "Aircraft",
        "MAKE": "Diamond",
        "CAMPUS": "DB",
        "SERIAL_NUM": "42.N539",
        "ETA_RESOURCE_ID": 5680,
        "LAST_KNOWN_TACH": "",
        "INSPECTION_BIT": 0,
        "PEDAL_EXT": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID_AS_EFC": 17,
        "INSPECTION_PLAN_ID": 4,
        "DATE_MODIFIED": "2026-09-22 00:32:47.262429 -04:00",
        "PARKING_SPOT_DETAILS": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID": 15,
        "PEDAL_POSITION": "",
        "VFR": 0,
        "FUEL_THRESHOLD": 48,
        "LAST_RAMP_IN_HOBBS": 1928.6,
        "MODEL": "DA42 NG",
        "LAST_RAMP_IN_TACH": 1345.9,
        "PARKING_SPOT_LAST_KNOWN_NAME": "A 09",
        "OBSOLETE": 0,
        "NAME": "N318ER",
        "RESOURCE_TYPE_NAME": "Diamond DA42-VI",
        "ACTIVE_PEDAL_REQUEST": 0,
        "HOBBS_TIME": "1928.6",
        "PEDAL_ABILITY": 0,
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_NAME_AS_EFC": "A 09",
        "FPC_ABILITY": 0,
        "NEXT_TACH_INSPECTION": "",
        "PARKING_SPOT_LAST_KNOWN_ID_AS_ETA": 15,
        "QRCODE1": "https://webapps.erau.edu/flight-clipboard/resourceqr/N318ER-K-1721648511638",
        "ENABLED": 1,
        "ETA_RESOURCE_CAT": "Aircraft",
        "PARKING_FBO": "",
        "TACH_TIME": "1345.9",
        "QRCODE2": "https://webapps.erau.edu/flight-clipboard/resourceqr/N318ER-P-1721648512422"
      }
    },
    {
      "DATE_MODIFIED": "2026-09-22 00:23:40.056533 -04:00",
      "DATE_CREATED": "2026-09-22 00:26:40.520000 -04:00",
      "RESOURCE_ID": 281,
      "DETAILS": {
        "PARKING_SPOT_ID": 103,
        "OIL": 0,
        "PARKING_SPOT": {
          "DATE_MODIFIED": "2021-07-20 12:56:37.000000 -04:00",
          "ETA_PARK_SPOT_ID": 61,
          "DATE_CREATED": "2021-07-20 12:56:37.000000 -04:00",
          "PARKING_SPOT_ID": 103,
          "RESOURCES": "",
          "CAMPUS": "DB",
          "RESOURCE_ID": "",
          "ENABLED": 1,
          "PREVENT_AF_REQ": 0,
          "OBSOLETE": 0,
          "NAME": "B 27"
        },
        "DENY_REASON_DETAILS": "",
        "REQUEST_FUEL_OIL_ID": 417614,
        "FUEL": 1,
        "THIRD_PARTY_DATA": {
          "REQUESTED_SERVICE": "Fill to tabs",
          "REQUESTED_AMOUNT": ""
        },
        "DENY_REASON_ID": ""
      },
      "MODE": "Aircraft",
      "RESPONDING_USER_ID": "",
      "REQUEST_ID": 2721397,
      "ACTIVITY_ID": "",
      "DATE_COMPLETED": "",
      "INITIATING_USER_ID": 2,
      "PARENT_ID": 0,
      "INITIATOR": {
        "DATE_MODIFIED": "2023-11-22 13:35:07.478000 -05:00",
        "DATE_CREATED": "2023-11-22 13:35:07.478000 -05:00",
        "USER_ID": 2,
        "EMAIL": "noreply@erau.edu",
        "LAST_NAME": "Automated",
        "SELECTED_RESOURCE_SLOT_SUM": "",
        "ERAU_ID": "0000000",
        "FIRST_NAME": "Request",
        "NAME": "Request Automated (0000000)",
        "EFC_CAMPUS": "",
        "LOC_ID": "",
        "ETA_ID": "",
        "ROLES": "",
        "SELECTED_ACTIVITY_ID": "",
        "USERNAME": "system",
        "ENABLED": 1,
        "SELECTED_RESOURCE_ID": "",
        "PHONE_NUMBER": "",
        "ETA_PERS_ID": -1
      },
      "NOTES": "",
      "TYPE_ID": 3,
      "PARENTED": 0,
      "REQUEST_TYPE": "Fuel/Oil",
      "STATUS_ID": 5,
      "RESOURCE": {
        "DATE_CREATED": "2022-04-29 11:33:23.000000 -04:00",
        "RESOURCE_ID": 281,
        "PARKING_SPOT_LAST_KNOWN_ID": 103,
        "RESOURCE_CAT": "Aircraft",
        "MAKE": "Cessna",
        "CAMPUS": "DB",
        "SERIAL_NUM": "172S12792",
        "ETA_RESOURCE_ID": 4761,
        "LAST_KNOWN_TACH": "",
        "INSPECTION_BIT": 0,
        "PEDAL_EXT": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID_AS_EFC": 103,
        "INSPECTION_PLAN_ID": 61,
        "DATE_MODIFIED": "2026-09-22 00:23:40.035758 -04:00",
        "PARKING_SPOT_DETAILS": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID": 61,
        "PEDAL_POSITION": "",
        "VFR": 0,
        "FUEL_THRESHOLD": 34,
        "LAST_RAMP_IN_HOBBS": 5659.8,
        "MODEL": "172S NAV III",
        "LAST_RAMP_IN_TACH": 4197,
        "PARKING_SPOT_LAST_KNOWN_NAME": "B 27",
        "OBSOLETE": 0,
        "NAME": "N818ER",
        "RESOURCE_TYPE_NAME": "Cessna 172S Nav3",
        "ACTIVE_PEDAL_REQUEST": 0,
        "HOBBS_TIME": "5659.8",
        "PEDAL_ABILITY": 0,
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_NAME_AS_EFC": "B 27",
        "FPC_ABILITY": 0,
        "NEXT_TACH_INSPECTION": "",
        "PARKING_SPOT_LAST_KNOWN_ID_AS_ETA": 61,
        "QRCODE1": "https://webapps.erau.edu/flight-clipboard/resourceqr/N818ER-K-1651247117672",
        "ENABLED": 1,
        "ETA_RESOURCE_CAT": "Aircraft",
        "PARKING_FBO": "",
        "TACH_TIME": "4197.0",
        "QRCODE2": "https://webapps.erau.edu/flight-clipboard/resourceqr/N818ER-P-1651247139903"
      }
    },
    {
      "DATE_MODIFIED": "2026-09-22 00:04:29.720822 -04:00",
      "DATE_CREATED": "2026-09-22 00:07:29.718000 -04:00",
      "RESOURCE_ID": 301,
      "DETAILS": {
        "PARKING_SPOT_ID": 151,
        "OIL": 0,
        "PARKING_SPOT": {
          "DATE_MODIFIED": "2021-07-20 12:57:47.000000 -04:00",
          "ETA_PARK_SPOT_ID": 7,
          "DATE_CREATED": "2021-07-20 12:57:47.000000 -04:00",
          "PARKING_SPOT_ID": 151,
          "RESOURCES": "",
          "CAMPUS": "DB",
          "RESOURCE_ID": "",
          "ENABLED": 1,
          "PREVENT_AF_REQ": 0,
          "OBSOLETE": 0,
          "NAME": "C 22"
        },
        "DENY_REASON_DETAILS": "",
        "REQUEST_FUEL_OIL_ID": 417612,
        "FUEL": 1,
        "THIRD_PARTY_DATA": {
          "REQUESTED_SERVICE": "Fill to tabs",
          "REQUESTED_AMOUNT": ""
        },
        "DENY_REASON_ID": ""
      },
      "MODE": "Aircraft",
      "RESPONDING_USER_ID": "",
      "REQUEST_ID": 2721369,
      "ACTIVITY_ID": "",
      "DATE_COMPLETED": "",
      "INITIATING_USER_ID": 2,
      "PARENT_ID": 0,
      "INITIATOR": {
        "DATE_MODIFIED": "2023-11-22 13:35:07.478000 -05:00",
        "DATE_CREATED": "2023-11-22 13:35:07.478000 -05:00",
        "USER_ID": 2,
        "EMAIL": "noreply@erau.edu",
        "LAST_NAME": "Automated",
        "SELECTED_RESOURCE_SLOT_SUM": "",
        "ERAU_ID": "0000000",
        "FIRST_NAME": "Request",
        "NAME": "Request Automated (0000000)",
        "EFC_CAMPUS": "",
        "LOC_ID": "",
        "ETA_ID": "",
        "ROLES": "",
        "SELECTED_ACTIVITY_ID": "",
        "USERNAME": "system",
        "ENABLED": 1,
        "SELECTED_RESOURCE_ID": "",
        "PHONE_NUMBER": "",
        "ETA_PERS_ID": -1
      },
      "NOTES": "",
      "TYPE_ID": 3,
      "PARENTED": 0,
      "REQUEST_TYPE": "Fuel/Oil",
      "STATUS_ID": 5,
      "RESOURCE": {
        "DATE_CREATED": "2022-05-10 09:29:32.000000 -04:00",
        "RESOURCE_ID": 301,
        "PARKING_SPOT_LAST_KNOWN_ID": 151,
        "RESOURCE_CAT": "Aircraft",
        "MAKE": "Cessna",
        "CAMPUS": "DB",
        "SERIAL_NUM": "172S12802",
        "ETA_RESOURCE_ID": 4782,
        "LAST_KNOWN_TACH": "",
        "INSPECTION_BIT": 0,
        "PEDAL_EXT": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID_AS_EFC": 151,
        "INSPECTION_PLAN_ID": 61,
        "DATE_MODIFIED": "2026-09-22 00:04:29.704059 -04:00",
        "PARKING_SPOT_DETAILS": "",
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_ID": 7,
        "PEDAL_POSITION": "",
        "VFR": 0,
        "FUEL_THRESHOLD": 34,
        "LAST_RAMP_IN_HOBBS": 1946.5,
        "MODEL": "172S NAV III",
        "LAST_RAMP_IN_TACH": 4075.2,
        "PARKING_SPOT_LAST_KNOWN_NAME": "C 22",
        "OBSOLETE": 0,
        "NAME": "N847ER",
        "RESOURCE_TYPE_NAME": "Cessna 172S Nav3",
        "ACTIVE_PEDAL_REQUEST": 0,
        "HOBBS_TIME": "1946.5",
        "PEDAL_ABILITY": 0,
        "ETA_RES_LAST_KNOWN_PARKING_SPOT_NAME_AS_EFC": "C 22",
        "FPC_ABILITY": 0,
        "NEXT_TACH_INSPECTION": "",
        "PARKING_SPOT_LAST_KNOWN_ID_AS_ETA": 7,
        "QRCODE1": "https://webapps.erau.edu/flight-clipboard/resourceqr/N847ER-K-1652196169735",
        "ENABLED": 1,
        "ETA_RESOURCE_CAT": "Aircraft",
        "PARKING_FBO": "",
        "TACH_TIME": "4075.2",
        "QRCODE2": "https://webapps.erau.edu/flight-clipboard/resourceqr/N847ER-P-1652196170531"
      }
    },
];

