import type { UserStatus, FuelerDashboardData } from "@/types/erau";
import type { FuelRequest } from "@/types/fuelRequest";

// Canned responses used when USE_MOCK_DATA=true, so the app is usable without campus network
// access. Taken verbatim from real payloads captured on 2026-09-20.

export const mockUserStatus: UserStatus = {
  environment: "production",
  user: {
    selectedResourceId: "0",
    etaPersId: "0",
    selectedResourceSlotSum: "0",
    phoneNumber: "",
    defaultPage: "",
    fileLabel: "",
    apLast4: "",
    firstName: "",
    email: "",
    accountMissing: false,
    loggedIn: false,
    selectedActivityId: "0",
    campus: "",
    pin: "",
    lastName: "",
    roles: [],
    userId: "0",
    themeIsDark: "false",
    enabled: false,
    erauId: "",
    inspectorNum: "",
    signatureId: "0",
  },
};

export const mockFuelerDashboardData: FuelerDashboardData = {
  sampleMessage: "fueler data from the server (mock)",
};

export const mockFuelRequests: FuelRequest[] = [
  {
    DATE_MODIFIED: "2026-09-20 01:26:30.837612 -04:00",
    DATE_CREATED: "2026-09-20 01:29:30.835000 -04:00",
    RESOURCE_ID: 801,
    DETAILS: {
      PARKING_SPOT_ID: 157,
      OIL: 0,
      PARKING_SPOT: {
        DATE_MODIFIED: "2021-07-20 12:57:59.000000 -04:00",
        ETA_PARK_SPOT_ID: 182,
        DATE_CREATED: "2021-07-20 12:57:59.000000 -04:00",
        PARKING_SPOT_ID: 157,
        CAMPUS: "DB",
        ENABLED: 1,
        PREVENT_AF_REQ: 0,
        OBSOLETE: 0,
        NAME: "C 25",
      },
      DENY_REASON_DETAILS: "",
      REQUEST_FUEL_OIL_ID: 416748,
      FUEL: 1,
      THIRD_PARTY_DATA: {
        REQUESTED_SERVICE: "Fill to tabs",
        REQUESTED_AMOUNT: "",
      },
      DENY_REASON_ID: "",
    },
    MODE: "Aircraft",
    REQUEST_ID: 2716419,
    DATE_COMPLETED: "",
    PARENT_ID: 0,
    INITIATOR: {
      USER_ID: 2,
      EMAIL: "noreply@erau.edu",
      LAST_NAME: "Automated",
      ERAU_ID: "0000000",
      FIRST_NAME: "Request",
      NAME: "Request Automated (0000000)",
      USERNAME: "system",
      ENABLED: 1,
    },
    NOTES: "",
    TYPE_ID: 3,
    PARENTED: 0,
    REQUEST_TYPE: "Fuel/Oil",
    STATUS_ID: 5,
    RESOURCE: {
      RESOURCE_ID: 801,
      RESOURCE_CAT: "Aircraft",
      MAKE: "Cessna",
      CAMPUS: "DB",
      SERIAL_NUM: "172S12979",
      NAME: "N923ER",
      MODEL: "172S NAV III",
      RESOURCE_TYPE_NAME: "Cessna 172S Nav3",
      PARKING_SPOT_LAST_KNOWN_NAME: "C 25",
      HOBBS_TIME: "4477.6",
      TACH_TIME: "3331.9",
    },
  },
  {
    DATE_MODIFIED: "2026-09-20 00:57:22.640265 -04:00",
    DATE_CREATED: "2026-09-20 01:00:22.638000 -04:00",
    RESOURCE_ID: 403,
    DETAILS: {
      PARKING_SPOT_ID: 153,
      OIL: 0,
      PARKING_SPOT: {
        DATE_MODIFIED: "2021-07-20 12:57:50.000000 -04:00",
        ETA_PARK_SPOT_ID: 79,
        DATE_CREATED: "2021-07-20 12:57:50.000000 -04:00",
        PARKING_SPOT_ID: 153,
        CAMPUS: "DB",
        ENABLED: 1,
        PREVENT_AF_REQ: 0,
        OBSOLETE: 0,
        NAME: "C 23",
      },
      DENY_REASON_DETAILS: "",
      REQUEST_FUEL_OIL_ID: 416746,
      FUEL: 1,
      THIRD_PARTY_DATA: {
        REQUESTED_SERVICE: "Fill to tabs",
        REQUESTED_AMOUNT: "",
      },
      DENY_REASON_ID: "",
    },
    MODE: "Aircraft",
    REQUEST_ID: 2716415,
    DATE_COMPLETED: "",
    PARENT_ID: 0,
    INITIATOR: {
      USER_ID: 2,
      EMAIL: "noreply@erau.edu",
      LAST_NAME: "Automated",
      ERAU_ID: "0000000",
      FIRST_NAME: "Request",
      NAME: "Request Automated (0000000)",
      USERNAME: "system",
      ENABLED: 1,
    },
    NOTES: "",
    TYPE_ID: 3,
    PARENTED: 0,
    REQUEST_TYPE: "Fuel/Oil",
    STATUS_ID: 5,
    RESOURCE: {
      RESOURCE_ID: 403,
      RESOURCE_CAT: "Aircraft",
      MAKE: "Cessna",
      CAMPUS: "DB",
      SERIAL_NUM: "172S12822",
      NAME: "N816ER",
      MODEL: "172S NAV III",
      RESOURCE_TYPE_NAME: "Cessna 172S Nav3",
      PARKING_SPOT_LAST_KNOWN_NAME: "C 23",
      HOBBS_TIME: "5284.7",
      TACH_TIME: "3900.2",
    },
  },
];

